### ISSUE TITLE
Task sourcesJar creates an empty jar

### ISSUE THREAD

**Issue by maciabit** [DanySK/maven-central-gradle-plugin#100]
Hi, i've encountered the following issue while using your plugin.  

Command `./gradlew sourcesJar` 

**Expected behaviour**: 
A jar containing the project's sources is created

**Actual behaviour**: 
The jar contains only the META-INF folder with a manifest file inside

**How to replicate the issue**: 
1. Init a new Gradle project (tested under Gradle 6.8.3 with both Scala and Java library projects)
2. Add the plugin in build.gradle.kts
3. Run `./gradlew sourcesJar` from the project root directory

The issue occurs only with the last two versions of the plugin (0.4.2 and 0.4.1), 0.4.0 seems to work fine.

**Comment by DanySK** [comment]
Can you provide a minimal example to reproduce?
My current guess is that something smelly's going on between the scala plugin and this one.

Other scala (or mixed scala+kotlin+java) projects seem to work and pack the jar correctly: https://search.maven.org/artifact/it.unibo.alchemist/alchemist-incarnation-scafi/10.0.1/jar

**Comment by maciabit** [comment]
The problem still occurs even with a newly created Java library Gradle project, you can refer to [this repository](https://github.com/maciabit/maven-central-gradle-sourcesJar) i just created to check the behaviour of the task. The build.gradle.kts file has the version 0.4.2 of the plugin, so the sources jar is empty. Changing the version to 0.4.0 makes the task work correctly.

Thanks in advance!

**Comment by DanySK** [comment]
So it regressed...

**Comment by DanySK** [comment]
@maciabit there is no `build.gradle.kts` in the linked project. I've run some tests and the plugin seems to generate the source jar correctly: can you fix the repository so that I have some way to reproduce?

Thanks

**Comment by DanySK** [comment]
Uh, actually, it's a strange multi-project without root

**Comment by DanySK** [comment]
OK, one easy workaround is to feed sources manually:
```kotlin
tasks.withType<org.danilopianini.gradle.mavencentral.SourcesJar> {
    sourceSet(sourceSets.main.get())
}
```

yet, it should be tracked automatically.

**Comment by DanySK** [comment]
@maciabit version 0.4.2-dev0g-e4cd624 should solve. Could you give it a spin?

**Comment by maciabit** [comment]
@DanySK 
Version 0.4.2-dev0g-e4cd624 fixes the issue, before that I've tried the workaround with the 0.4.2 version and that works too. The project structure of the repository I've linked seems to be the default in Gradle 6.8 unless you select a basic application when initializing the project.

**Comment by DanySK** [comment]
I see. I never used the automatically generated structure, I prefer to have full control over the structure of my projects.
Change has been reified in version 0.4.3, thanks for reporting.

Closing.
