### ISSUE TITLE
Please document PGP setup

### ISSUE THREAD

**Issue by mvysny** [DanySK/maven-central-gradle-plugin#87]
Hi, this is an awesome plugin which will hopefully simplify the complex deployment towards Maven Central :+1: 

However, I know that Maven Central requires PGP-signed artifacts (and your README suggests that the plugin will perform the signing automatically), however I can not find any docs on which key it will pick, how the key password is configured for the plugin etc.

**Comment by DanySK** [comment]
Hi @mvysny , thanks for pointing out the issue!
I added a note to the Readme file.
The plugin applies the `sign` plugin internally and pre-configures every publication to be signed, but it does not decide how to sign for you: you still need to have a `signing` block where to specify the options of your like as [documented in the Gradle guide](https://docs.gradle.org/current/userguide/signing_plugin.html).

As a source for inspiration, consider that this plugin uses itself to publish itself on Central, so its signing configuration can be copied.

**Comment by mvysny** [comment]
Perfect, thank you :+1: now it's easy to understand
