### ISSUE TITLE
Why not use vanniktech/gradle-maven-publish-plugin?

### ISSUE THREAD

**Issue by asarkar** [DanySK/maven-central-gradle-plugin#88]
There seems to be a Gradle plugin already for publishing to Maven Central.
https://github.com/vanniktech/gradle-maven-publish-plugin

What does your plugin do better? Honest question.

**Comment by DanySK** [comment]
I'm not sure there was that plugin when I began developing this.

Anyway, in my understanding the differences are:
1. This plugin does not rely on predefined properties
3. The plugin you linked is able to interact with Nexus. This one cannot, it simply uploads (it is a configuration automation system for Gradle publish, nothing more
4. This plugin focuses on Kotlin build scripts, the one you mention seems to focus on Groovy

My suggestion is to try both and see for your yourself which one suits your needs better.

**Comment by asarkar** [comment]
Given that [JCenter and Bintray are going to be decommissioned](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), people are looking for alternatives. An easy to use Maven Central publish plugin could really be useful. I'm not sure what you meant by the last point, since any Gradle plugin can be used with Groovy or Kotlin build scripts, as long as it has good documentation/examples.
I'm happy to give it a shot provided this plugin offers there a dry run feature. I don't want to experiment by publishing artifacts that I don't want to publish, given that once published, there's no way to delete them.

**Comment by asarkar** [comment]
Also, what does it mean to "interact with Nexus"?

**Comment by DanySK** [comment]
@asarkar 
for Kotlin/Groovy, I'm referring to documentation. I will not write documentation for Groovy build scripts (although I happily consider pull requests), as I consider it legacy. The guys at vanniktech/gradle-maven-publish-plugin seems instead to favor Groovy, so if one searches for a plugin they can select one first by the better documented language.

On Nexus/dry runs: Sonatype uses Nexus as repository management system, as you will discover once you try to publish your first artifact on Maven Central. Nexus provides a stage where packages are validated before release. Uploaded repositories need to be closed, and once closed they can be released. The vanniktech/gradle-maven-publish-plugin provides (as I understand) means to run these operations from Gradle. This plugin does not.
This is also the reason why a dry-run is not necessary for Central: your uploaded package are not released automatically. An access to https://oss.sonatype.org/ is required anyway. You can give a spin to this plugin safely, as far as you point to Central.

This plugin is really just a nice configurator for Gradle's Publish Plugin, so it will support explicit dry-runs as soon as the Gradle Publish Plugin will support them. If you need features the Gradle Publish plugin does not provide (like the mentioned Sonatype Nexus interaction), you should search them elsewhere.

**Comment by asarkar** [comment]
> Groovy build scripts ... as I consider it legacy

This is your assumption, and not a fact supported by Gradle, as there exists no documentation that says so. But, of course, being the owner of the plugin, and not having bunch of other maintainers, you've the choice to make decisions as you see fit without much debate.

I understand now what you mean by interacting with Nexus. Staging is a mandatory step for publishing to Central, so if the plugin doesn't support it, the user will have to find some alternative means to do that. Not very convenient for them.

I think I'm leaning towards the vanniktech/gradle-maven-publish-plugin, but I'll know for sure when I actually use it. Currently, I see they are undergoing a substantial API change.

I'm closing this ticket since my questions have been answered. If I've other questions, I'll open new tickets. Thank you.
