### ISSUE TITLE
Use publishing credentials instead of env var

### ISSUE THREAD

**Issue by asarkar** [DanySK/maven-central-gradle-plugin#89]
According to the README:
> The plugin is pre-configured to fetch credentials for Maven Central from the environment
> Username from: MAVEN_CENTRAL_USERNAME
> Password from: MAVEN_CENTRAL_PASSWORD

Gradle credentials offer an abstraction so that the actual values may come of one of many sources. This is the recommended way to handle credentials in modern builds.
https://docs.gradle.org/current/samples/sample_publishing_credentials.html 

```
repositories {
    maven {
        name = "mySecureRepository"
        credentials(PasswordCredentials::class)
        // url = uri(<<some repository url>>)
    }
}
```

**Comment by DanySK** [comment]
Hi  @asarkar,
environment variables are supported for retrocompatibility. The plugin is already configurable in this sense:
it tries to retrieve information from the environment variables `MAVEN_CENTRAL_USERNAME` and `MAVEN_CENTRAL_PASSWORD`, but in case they are undefined it automatically falls back to project properties `mavenCentralUsername` and `mavenCentralPassword`, that you can specify exactly as you would using the example you provided (the plugin actually uses that system internally).

Let me know if this solves your doubts

**Comment by asarkar** [comment]
> falls back to project properties `mavenCentralUsername` and `mavenCentralPassword`

These keys are dependent on the repository name, so if someone names a publishing repo as `mySecureRepository` (as in my example), the keys will be `mySecureRepositoryUsername` and `mySecureRepositoryPassword`. If you're looking for hard coded key names, then no, the plugin is not compliant with the Gradle credentials.

**Comment by DanySK** [comment]
They are not. They are **exactly** the property names. They are fixed and not depending on anything of your project, and they are valid exclusively for Maven Central.

If your project name is `foo`, then the keys are `mavenCentralUsername` and `mavenCentralPassword`. If your project name is `bar`, then the keys still are `mavenCentralUsername` and `mavenCentralPassword`.

You can (but should not for security reasons) write them in your `gradle.properties`:

```
mavenCentralUsername=YOUR_OSSRH_USERNAME
mavenCentralPassword=YOUR_OSSRH_PASSWORD
```
Or you can pass them from the command line:
``./gradlew publish -PmavenCentralUsername=YOUR_OSSRH_USERNAME -PmavenCentralPassword=YOUR_OSSRH_PASSWORD``

Or you can specify them in your user home `gradle.properties`, or you can use the gradle environment variables name convention and use environment variables named `ORG_GRADLE_PROJECT_mavenCentralUsername` and `ORG_GRADLE_PROJECT_mavenCentralPassword`.

To learn more about the Gradle project properties: https://docs.gradle.org/current/userguide/build_environment.html#sec:project_properties


If you want to setup credentials for targets other than Central, that's fully customizable:
```kotlin
publishOnCentral {
    repository("https://YourCompanyPrivateRepositoryUri", "mySecureRepository") {
        user = TODO() // Here you can access project properties, env variables, or do what you please, it is pure Kotlin
        password = TODO() // Here as well, of course.
    }
}
```
This configuration will automatically create tasks `publishJavaMavenPublicationToMySecureRepositoryRepository`, `publishKotlinPublicationToMySecureRepositoryRepository`, and so on, one for each software component your or the plugins you applied defined.

Internally, the plugin runs the same configuration you mentioned from the doc. It really is an automatic configurator for the official Gradle Publish plugin, it does no magic.

Hope this clarifies!

**Comment by DanySK** [comment]
(by the way, as an example, you can see how this plugin publishes itself on github packages, which use credentials that differ from Maven Central's)
